repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
        additional_dependencies: []
        types_or: [python]
        files: ^backend/|
      - id: ruff-format
        types_or: [python]
        files: ^backend/|

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        types_or: [python]
        files: ^backend/|

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: []
        files: ^backend/|
        args: ["--config-file=pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.0
    hooks:
      - id: eslint
        name: eslint (frontend)
        files: ^frontend/src/|
        additional_dependencies:
          - eslint@8.57.0
          - eslint-plugin-react@7.37.2

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        name: prettier (frontend)
        files: ^frontend/|
